###服务端口
server:
  port: 8181

spring:
  application:
    name: actor-manage
  profiles:
    active: dev
---

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/audio?serverTimezone=GMT%2B8
    username: root
    password: a1b2c3

# mybatis 日志
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
hikari:
  connection-test-query: SELECT 1
connection-timeout: 60000
idle-timeout: 500000
max-lifetime: 540000
maximum-pool-size: 12
minimum-idle: 10
pool-name: GuliHikariPool
jackson:
  date-format: yyyy-MM-dd HH:mm:ss
time-zone: GMT+8

