
spring:
  profiles:
    active: dev
server:
  port: 8181
---
#mysql数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/audio?serverTimezone=GMT%2B8
    username: root
    password: a1b2c3

#mybatis日志 可以看到里面 sql 操作详细数据
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl